runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: blog.app


libraries:
- name: jinja2
  version: latest
